import { PassengerTrip, PopularRoute } from './types';

export const mockPopularRoutes: PopularRoute[] = [
  { id: 'p1', origin: 'Hyderabad', destination: 'Bengaluru', priceEstimate: 850 },
  { id: 'p2', origin: 'Mumbai', destination: 'Pune', priceEstimate: 450 },
  { id: 'p3', origin: 'Delhi', destination: 'Jaipur', priceEstimate: 600 },
  { id: 'p4', origin: 'Chennai', destination: 'Bengaluru', priceEstimate: 750 },
];

export const mockPassengerTrips: PassengerTrip[] = [
  {
    id: 'trip-101',
    driverName: 'Vikram Singh',
    driverRating: 4.9,
    totalRides: 142,
    isVerifiedDriver: true,
    origin: 'Hyderabad',
    destination: 'Bengaluru',
    departureTime: '06:30 AM',
    departureIso: '2026-08-18T06:30:00Z',
    arrivalTime: '02:30 PM',
    duration: '8h 00m',
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 850,
    vehicleType: 'SUV',
    vehicleModel: 'Toyota Innova Crysta',
  },
  {
    id: 'trip-102',
    driverName: 'Ananya Sharma',
    driverRating: 4.95,
    totalRides: 88,
    isVerifiedDriver: true,
    origin: 'Hyderabad',
    destination: 'Bengaluru',
    departureTime: '08:15 AM',
    departureIso: '2026-08-18T08:15:00Z',
    arrivalTime: '04:00 PM',
    duration: '7h 45m',
    availableSeats: 2,
    totalSeats: 4,
    pricePerSeat: 780,
    vehicleType: 'Sedan',
    vehicleModel: 'Honda City i-VTEC',
  },
  {
    id: 'trip-103',
    driverName: 'Rajesh Kumar',
    driverRating: 4.75,
    totalRides: 210,
    isVerifiedDriver: true,
    origin: 'Hyderabad',
    destination: 'Bengaluru',
    departureTime: '02:00 PM',
    departureIso: '2026-08-18T14:00:00Z',
    arrivalTime: '10:00 PM',
    duration: '8h 00m',
    availableSeats: 4,
    totalSeats: 4,
    pricePerSeat: 700,
    vehicleType: 'EV',
    vehicleModel: 'Tata Nexon EV Max',
  },
  {
    id: 'trip-104',
    driverName: 'Siddharth Rao',
    driverRating: 4.88,
    totalRides: 64,
    isVerifiedDriver: true,
    origin: 'Hyderabad',
    destination: 'Bengaluru',
    departureTime: '06:00 PM',
    departureIso: '2026-08-18T18:00:00Z',
    arrivalTime: '02:00 AM',
    duration: '8h 00m',
    availableSeats: 1,
    totalSeats: 4,
    pricePerSeat: 920,
    vehicleType: 'SUV',
    vehicleModel: 'Mahindra XUV700',
  },
  {
    id: 'trip-105',
    driverName: 'Priya Verma',
    driverRating: 4.82,
    totalRides: 115,
    isVerifiedDriver: true,
    origin: 'Mumbai',
    destination: 'Pune',
    departureTime: '07:00 AM',
    departureIso: '2026-08-18T07:00:00Z',
    arrivalTime: '10:00 AM',
    duration: '3h 00m',
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 450,
    vehicleType: 'Sedan',
    vehicleModel: 'Hyundai Verna',
  },
];
